### ISSUE TITLE
Test set and valid set about Tmall

### ISSUE THREAD

**Issue by 30CodeMaker** [xizhu1022/DA-GCN#2]
Hello author, I found that the test set and validation set on your Tmall data set are exactly the same, may I ask whether the wrong data set was uploaded or this is the original one ?

**Comment by xizhu1022** [comment]
Thanks for reaching out. 
We are confident that our code includes correct validation. However, to ensure a fair comparison, we use the same datasets as previous studies. Specifically, the Tmall dataset aligns with MB-CGCN, and the Taobao dataset is shared with EHCF and GHCF, especially including their data splits. It seems that they might have missed a validation set. Additionally, we have included other datasets with proper validation sets in `'./data'` for further studies.
